- title: Image Recognition
  icon: basic-elaboration-smartphone-heart
  content: When designing a product, we always think of how the user is going to experience it.
- title: Predictive Modeling
  icon: basic-elaboration-message-happy
  content: No matter what you're stuck with, our support team will respond in the most adequate manner.
- title: Recommendations System
  icon: basic-lightbulb
  content: Your fantasy is the limit here. Using our elements you can make anything come true.
- title: Big Data
  icon: basic-lock
  content: We don't take cyber security lightly, that's why our team put a lot of effort into securing this app.
- title: Data mining
  icon: basic-bolt
  content: Powered by Materialize, this theme doesn't require page reloads, providing a seamless user experience.
- title: Consultation and Training service
  icon: software-eyedropper
  content: Hand crafted with material design principles, with a focus on readability and white spaces.